# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            purplefabr
tagline:          'fabricating the future'
description:      'purplefabr.<br>Simple designs for DIY fabrication.<br>Made by <a href="https://github.com/macaba" target="_blank">@macaba</a>.'
url:              http://purplefabr.github.io
baseurl:          http://purplefabr.github.io/

author:
  name:           'macaba'
  url:            https://github.com/macaba

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/purplefabr
